-- LOAD THESE AFTER LOADING DATA
-- In table definitions, references are just comments
alter table states add foreign key (country) references countries(code);
alter table ips add foreign key (country) references countries(code);
alter table people add foreign key (country) references countries(code);
alter table admins add foreign key (person_id) references people(id);
alter table admin_auths add foreign key (person_id) references people(id);
alter table admin_log add foreign key (person_id) references people(id);
alter table ats add foreign key (person_id) references people(id) on delete cascade;
alter table urls add foreign key (person_id) references people(id) on delete cascade;
alter table ptags add foreign key (person_id) references people(id) on delete cascade;
alter table utags add foreign key (person_id) references people(id) on delete cascade;
alter table stats add foreign key (person_id) references people(id) on delete cascade;
alter table temps add foreign key (person_id) references people(id) on delete cascade;
alter table logins add foreign key (person_id) references people(id) on delete cascade;
alter table emails add foreign key (person_id) references people(id);
alter table emails add foreign key (created_by) references people(id);
alter table emails add foreign key (opened_by) references people(id);
alter table emails add foreign key (closed_by) references people(id);
alter table emails add foreign key (reference_id) references emails(id);
alter table attachments add foreign key (email_id) references emails(id) on delete cascade;
alter table listpeople add foreign key (list_id) references lists(id);
alter table listpeople add foreign key (email) references ats(email);
alter table interviews add foreign key (person_id) references people(id);
alter table utterances add foreign key (interview_id) references interviews(id);
alter table availabilities add foreign key (interview_id) references interviews(id);
alter table availabilities add foreign key (person_id) references people(id);
alter table meetings add foreign key (where_id) references meetwheres(id);
alter table meetings add foreign key (person_id) references people(id);
alter table meetavails add foreign key (where_id) references meetwheres(id);
alter table meetavails add foreign key (person_id) references people(id);
alter table meetavails add foreign key (meeting_id) references meetings(id);
alter table now_pages add foreign key (person_id) references people(id) on delete cascade;
alter table now_pages add foreign key (checked_by) references people(id) on delete set null;
alter table now_pages add foreign key (review_by) references people(id) on delete set null;
alter table now_profiles add foreign key (id) references people(id) on delete cascade;
alter table books add foreign key (metabook_id) references metabooks(id);
alter table books add foreign key (lang) references langs(code);
alter table metabooks add foreign key (title_code) references sentences(code);
alter table metabooks add foreign key (subtitle_code) references sentences(code);
alter table articles add foreign key (title_code) references sentences(code);
alter table formats add foreign key (book_id) references books(id);
alter table formats add foreign key (isbn) references isbns(isbn);
alter table sentences add foreign key (article_id) references articles(id);
alter table hrefs add foreign key (sentence_code) references sentences(code);
alter table sections add foreign key (metabook_id) references metabooks(id);
alter table sections add foreign key (title_code) references sentences(code);
alter table chapters add foreign key (metabook_id) references metabooks(id);
alter table chapters add foreign key (article_id) references articles(id);
alter table chapters add foreign key (section_id) references sections(id);
alter table posts add foreign key (article_id) references articles(id);
alter table translators add foreign key (person_id) references people(id);
alter table translators add foreign key (lang) references langs(code);
alter table translators add foreign key (metabook_id) references metabooks(id);
alter table transjury add foreign key (person_id) references people(id);
alter table transjury add foreign key (lang) references langs(code);
alter table translations add foreign key (sentence_code) references sentences(code);
alter table translations add foreign key (lang) references langs(code);
alter table translations add foreign key (by) references people(id);
alter table transquestions add foreign key (translation_id) references translations(id);
alter table transquestions add foreign key (by) references people(id);
alter table transquestions add foreign key (code) references sentences(code);
alter table transjudgements add foreign key (translation_id) references translations(id) on delete cascade;
alter table transjudgements add foreign key (by) references people(id);
alter table comments add foreign key (person_id) references people(id) on delete cascade;
alter table videotext add foreign key (video_id) references videos(id);
alter table videotext add foreign key (sentence_code) references sentences(code);
alter table country_currency add foreign key (country) references countries(code);
alter table country_currency add foreign key (currency) references currencies(code);
alter table feeditems add foreign key (feed_uri) references feeds(uri);
alter table feeditems add foreign key (article) references articles(id);
alter table metaitems add foreign key (price_id) references prices(id);
alter table items add foreign key (metaitem_id) references metaitems(id);
alter table items add foreign key (price_id) references prices(id);
alter table warehouses add foreign key (country) references countries(code);
alter table invoices add foreign key (person_id) references people(id);
alter table invoices add foreign key (warehouse) references warehouses(country);
alter table invoices add foreign key (add2) references invoices(id);
alter table invoices add foreign key (currency) references currencies(code);
alter table invoices add foreign key (country) references countries(code);
alter table lineitems add foreign key (invoice_id) references invoices(id) on delete cascade;
alter table lineitems add foreign key (item_id) references items(id) on delete restrict;
alter table postzones add foreign key (warehouse) references warehouses(country);
alter table postzones add foreign key (country) references countries(code);
alter table downloadables add foreign key (metaitem_id) references metaitems(id);
alter table praise add foreign key (person_id) references people(id);
alter table praise add foreign key (metaitem_id) references metaitems(id);
alter table reactions add foreign key (person_id) references people(id);
alter table reactions add foreign key (metaitem_id) references metaitems(id);
alter table ebooknotes add foreign key (ebook_code) references ebooks(code);

