-- static HTML comments, by Derek Sivers. Article: https://sive.rs/shc

create table comments (
  id integer primary key generated by default as identity,
  uri text,
  created_at date default current_date,
  name text,
  email text,
  comment text
);
create index on comments(uri);
