-- after tempcode generated by o.temp_add
-- email that tempcode to them, given the domain
create function o.temp_email(_tempcode text, _domain text, out id integer) as $$
declare
	pid integer;
	name text;
	email text;
	body text;
begin
	-- coalesce whether they're in people table or only in temps
	select temps.person_id,
	coalesce(people.name, temps.new_name),
	coalesce(o.email_for(temps.person_id), temps.new_email)
	into pid, name, email
	from temps
	left join people on temps.person_id = people.id
	where temps.temp = $1;
	if email is not null then
		body = 'Hi ' || name || e' -\n\nYour link to log in now:\n\nhttps://' || $2 || '/e?t=' || $1;
		-- maybe some day, if it's a problem, if people are clicking too many times,
		-- check if same body, subject, and category are recently (10 minutes?) in emails before adding again
	insert into emails (person_id, category,
			created_at, created_by, opened_at, opened_by, closed_at, closed_by,
			their_email, their_name, subject, body, outgoing)
		values (pid, 'templink',
			now(), 0, now(), 0, now(), 0,
			email, name, 'your login link for ' || $2, body, null)
		returning emails.id into id;
	end if;
end;
$$ language plpgsql;

